// Auto-generated by C10 ARCH-1
// Helpers de api/reports/generate-technical.ts

export function sanitize(s: unknown): string {
  return String(s ?? '').replace(/[\x00-\x1F\x7F]/g, '').trim();
}

export function serializeField(val: unknown): string {
  if (typeof val === 'string') return val;
  try { return JSON.stringify(val, null, 2); } catch { return String(val); }
}

export function parseConfidence(val: unknown): number {
  if (typeof val === 'number' && Number.isFinite(val)) {
    if (val > 1) return val / 100;
    return Math.max(0, val);
  }
  if (typeof val === 'string') {
    const text = val.trim().replace(',', '.');
    if (!text) return 0;
    const normalized = text.replace(/%$/, '');
    const parsed = Number(normalized);
    if (!Number.isFinite(parsed) || parsed < 0) return 0;
    return text.endsWith('%') || parsed > 1 ? parsed / 100 : parsed;
  }
  return 0;
}

export function removeAiDuplicateSections(text: string): string {
  return text
    .replace(/(?:^|\n)(Landmarks Anat[oô]micos:|Recomenda[cç][oõ]es:|Fatores de Risco:)[\s\S]*?(?=\n(?:Landmarks Anat[oô]micos:|Recomenda[cç][oõ]es:|Fatores de Risco:)|$)/gi, '')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

export const SPECIES_MAP: Record<string, string> = {
  canine: 'Canina',
  feline: 'Felina',
  equine: 'Equina',
  bovine: 'Bovina',
  avian: 'Aviária',
  reptile: 'Réptil',
  other: 'Outra',
};

export const PROCEDURE_MAP: Record<string, string> = {
  orthopedic: 'Ortopédico',
  fracture: 'Fratura',
  radiography: 'Radiografia',
  surgery: 'Cirurgia',
  consultation: 'Consulta',
  other: 'Outro',
};

export const STATUS_MAP: Record<string, string> = {
  pending: 'Pendente',
  in_analysis: 'Em Análise',
  completed: 'Concluído',
  critical: 'Crítico',
};

export function translateEnum(val: unknown, map: Record<string, string>): string {
  const s = sanitize(val).toLowerCase();
  return map[s] || (s ? s.charAt(0).toUpperCase() + s.slice(1) : '—');
}

export function field(val: unknown): string {
  const s = sanitize(val);
  if (!s || s.toLowerCase() === 'sem nome' || s === '0') return '—';
  return s;
}

export function addLine(doc: any, text: string, x: number, y: number, maxWidth: number, lineHeight: number = 6): number {
  const split = doc.splitTextToSize(text, maxWidth);
  for (const line of split) {
    if (y > 270) {
      doc.setFontSize(9);
      doc.text('Vanguard Veterinary — Ortopedia Veterinária', 15, 287, { charSpace: 0 });
      doc.addPage();
      y = 20;
      doc.setFontSize(10);
    }
    doc.text(line, x, y, { charSpace: 0 });
    y += lineHeight;
  }
  return y;
}

export function stripPdfNotes(text: string): string {
  if (!text) return '';
  let cleaned = text;

  const copilotMatch = cleaned.match(/---\s*Hist[óo]rico\s+Copiloto[\s\S]*$/i);
  if (copilotMatch) {
    cleaned = cleaned.substring(0, copilotMatch.index);
  }

  cleaned = cleaned.replace(/---\s*Análise IA.*?---/g, '');
  cleaned = cleaned.replace(/```[\s\S]*?(?:```|$)/g, '');
  cleaned = cleaned.replace(/\[[^\]\n]*(?:OrthoAI|OrtoAI)[^\]\n]*\]\s*/gi, '');
  cleaned = cleaned.replace(/\[?\u00d8=\u00dci[^\]\n]*\]\s*/gi, '');
  cleaned = cleaned.replace(/((?:[A-Za-zÀ-ÿ\u00C0-\u00FF][ \u00A0]){6,}[A-Za-zÀ-ÿ\u00C0-\u00FF])/g, (m) => m.replace(/[ \u00A0]/g, ''));
  cleaned = cleaned.replace(/^\s*\|.*\|\s*$/gm, '');
  cleaned = cleaned.replace(/^\s*\|[-:\s|]+\|\s*$/gm, '');
  cleaned = cleaned.replace(/#{1,4}\s+/g, '');
  cleaned = cleaned.replace(/\*\*(.+?)\*\*/g, '$1');
  cleaned = cleaned.replace(/\*(.+?)\*/g, '$1');
  cleaned = cleaned.replace(/^\|[-\s|:]+\|$/gm, '');
  cleaned = cleaned.replace(/\|/g, ' — ');
  cleaned = cleaned.replace(/^---+$/gm, '');
  cleaned = cleaned.replace(/\[\[.*?\]\]/g, '');
  cleaned = cleaned.replace(/\[(.*?)\]\(.*?\)/g, '$1');
  cleaned = cleaned.replace(/\n{3,}/g, '\n\n');
  cleaned = cleaned.replace(/[ \t]{2,}/g, ' ');

  return cleaned.trim();
}

