import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import React, { useState } from 'react';
import { Award, BarChart3, Edit2, Check, X } from 'lucide-react';
import { useApp } from '@/contexts/AppContext';
import { Card, Button, Badge, SectionHeader } from '@/components/ui';
import { RadarChart, Radar, PolarGrid, PolarAngleAxis, PolarRadiusAxis, ResponsiveContainer } from 'recharts';
const RADAR_DATA = [
    { subject: 'TPLO', A: 97 }, { subject: 'FHO', A: 92 }, { subject: 'TTA', A: 88 },
    { subject: 'Espinhal', A: 78 }, { subject: 'Fraturas', A: 85 }, { subject: 'Próteses', A: 80 },
];
export default function ProfilePage() {
    const { user, setCurrentPage } = useApp();
    const [editMode, setEditMode] = useState(false);
    const [editName, setEditName] = useState(user?.name || '');
    const [editSpec, setEditSpec] = useState(user?.specialty || '');
    if (!user)
        return null;
    return (_jsxs("div", { className: "p-6 max-w-4xl space-y-6", children: [_jsx(SectionHeader, { title: "Perfil Profissional", subtitle: "Dados, certifica\u00E7\u00F5es e desempenho" }), _jsx(Card, { className: "p-6", children: _jsxs("div", { className: "flex items-start gap-5", children: [_jsx("div", { className: "w-20 h-20 rounded-2xl bg-[#0056b3] flex items-center justify-center text-white text-3xl font-bold flex-shrink-0", children: user.name.charAt(0) }), _jsx("div", { className: "flex-1 min-w-0", children: editMode ? (_jsxs("div", { className: "space-y-3", children: [_jsx("input", { value: editName, onChange: e => setEditName(e.target.value), className: "w-full border border-slate-200 rounded-lg px-3 py-2 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-[#0056b3]" }), _jsx("input", { value: editSpec, onChange: e => setEditSpec(e.target.value), className: "w-full border border-slate-200 rounded-lg px-3 py-2 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-[#0056b3]" }), _jsxs("div", { className: "flex gap-2", children: [_jsxs(Button, { size: "sm", onClick: () => setEditMode(false), children: [_jsx(Check, { size: 13 }), " Salvar"] }), _jsxs(Button, { size: "sm", variant: "secondary", onClick: () => setEditMode(false), children: [_jsx(X, { size: 13 }), " Cancelar"] })] })] })) : (_jsxs(_Fragment, { children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("h2", { className: "text-xl font-bold text-slate-900", style: { fontFamily: 'Montserrat' }, children: editName || user.name }), _jsx("button", { onClick: () => setEditMode(true), className: "text-slate-400 hover:text-[#0056b3] transition-colors", children: _jsx(Edit2, { size: 14 }) })] }), _jsx("p", { className: "text-sm text-slate-500 mt-0.5", children: editSpec || user.specialty }), _jsxs("div", { className: "flex flex-wrap gap-2 mt-3", children: [_jsx(Badge, { variant: "blue", children: user.crmv }), _jsx(Badge, { variant: "info", children: user.role === 'veterinarian' ? 'Médico Veterinário' : user.role }), _jsx(Badge, { variant: "default", children: user.institution })] })] })) })] }) }), _jsx("div", { className: "grid grid-cols-2 md:grid-cols-4 gap-4", children: [
                    { label: 'Total de Casos', value: user.stats.totalCases, color: '#0056b3' },
                    { label: 'Taxa de Sucesso', value: `${user.stats.successRate}%`, color: '#059669' },
                    { label: 'Precisão Média', value: `${user.stats.avgPrecision}%`, color: '#0891b2' },
                    { label: 'Procedimentos/Mês', value: user.stats.monthlyProcedures, color: '#d97706' },
                ].map(({ label, value, color }) => (_jsxs(Card, { className: "p-4 text-center", children: [_jsx("p", { className: "text-2xl font-bold font-mono", style: { color }, children: value }), _jsx("p", { className: "text-xs text-slate-500 mt-1 font-semibold", children: label })] }, label))) }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-5", children: [_jsxs(Card, { className: "p-5", children: [_jsx(SectionHeader, { title: "Certifica\u00E7\u00F5es", subtitle: `${user.certifications.length} certificados` }), _jsx("div", { className: "space-y-3", children: user.certifications.map(cert => (_jsxs("div", { className: "flex items-start gap-3 p-3 bg-slate-50 rounded-xl", children: [_jsx("div", { className: "w-8 h-8 rounded-lg bg-[#0056b3]/10 flex items-center justify-center flex-shrink-0", children: _jsx(Award, { className: "h-4 w-4 text-[#0056b3]" }) }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("p", { className: "text-sm font-semibold text-slate-900 leading-tight", children: cert.title }), _jsxs("p", { className: "text-xs text-slate-500 font-mono mt-0.5", children: [cert.issuer, " \u00B7 ", cert.year] })] }), cert.verified && _jsxs(Badge, { variant: "success", children: [_jsx(Check, { size: 9, className: "mr-0.5" }), "Verificado"] })] }, cert.id))) }), _jsx(Button, { variant: "secondary", size: "sm", className: "w-full mt-4", children: "+ Adicionar Certifica\u00E7\u00E3o" })] }), _jsxs(Card, { className: "p-5", children: [_jsx(SectionHeader, { title: "Compet\u00EAncias T\u00E9cnicas", subtitle: "Score por procedimento" }), _jsx(ResponsiveContainer, { width: "100%", height: 220, children: _jsxs(RadarChart, { data: RADAR_DATA, margin: { top: 10, right: 20, bottom: 10, left: 20 }, children: [_jsx(PolarGrid, { stroke: "#e2e8f0" }), _jsx(PolarAngleAxis, { dataKey: "subject", tick: { fontSize: 11, fill: '#64748b', fontFamily: 'Roboto Mono' } }), _jsx(PolarRadiusAxis, { angle: 90, domain: [0, 100], tick: { fontSize: 9, fill: '#94a3b8' } }), _jsx(Radar, { dataKey: "A", stroke: "#0056b3", fill: "#0056b3", fillOpacity: 0.15, strokeWidth: 2, dot: { r: 3, fill: '#0056b3' } })] }) })] })] }), _jsxs("div", { className: "flex flex-wrap gap-3", children: [_jsxs(Button, { variant: "secondary", size: "sm", onClick: () => setCurrentPage('reports'), children: [_jsx(BarChart3, { size: 13 }), " Ver Relat\u00F3rios"] }), _jsx(Button, { variant: "secondary", size: "sm", onClick: () => setCurrentPage('gallery'), children: "Ver Hist\u00F3rico de Casos" }), _jsx(Button, { variant: "secondary", size: "sm", onClick: () => setCurrentPage('settings'), children: "Configura\u00E7\u00F5es de Conta" })] })] }));
}
